version: 1
LastOpenTab: Anywhere
CurrentProfileName: default
CurrentRegion: us-west-2
UserProfiles: >+
  - Region: us-west-2

    Name: Omar

    BucketName: 

    AnywhereFleetName: 

    AnywhereFleetId: 

    AnywhereFleetLocation: 

    ComputeName: 

    IpAddress: 

    WebSocketUrl: 

    ContainerDeploymentInProgress: false

    ContainersDeploymentComplete: false

    ContainerQuestionnaireScenario: NoContainerImageNoExistingEcrRepo

    ContainerDeploymentScenario: SingleRegion

    ContainerEnableMetrics: false

    ContainerGameServerBuildPath: 

    ContainerGameServerExecutable: 

    ContainerDockerImageId: 

    ContainerECRRepositoryName: 

    ContainerECRRepositoryUri: 

    ContainerECRImageUri: 

    ContainerECRImageId: 

    ContainerPortRange: 

    ContainerTotalMemory: 

    ContainerTotalVcpu: 

    ContainerGameName: 

    ContainerImageTag: 

    IsContainerImageBuilding: false

    IsContainerImageBuilt: false

    IsECRRepoCreated: false

    IsContainerPushedToECR: false

    IsCGDDeploying: false

    IsCGDDeployed: false

    DeploymentScenario: SingleRegion

    DeploymentGameName: 

    ManagedEC2FleetName: 

    BuildName: 

    LaunchParameters: 

    BuildOperatingSystem: 

    EnableMetrics: false

    DeploymentBuildFilePath: 

    DeploymentBuildFolderPath: 

  - Region: us-west-2

    Name: default

    BucketName: highstreet-dev

    AnywhereFleetName: OmarFleet

    AnywhereFleetId: fleet-df9064c7-c563-4276-b905-4826dd766875

    AnywhereFleetLocation: custom-lobby-01

    ComputeName: OmarPc

    IpAddress: 100.111.137.81

    WebSocketUrl: wss://us-west-2.api.amazongamelift.com

    ContainerDeploymentInProgress: false

    ContainersDeploymentComplete: false

    ContainerQuestionnaireScenario: NoContainerImageNoExistingEcrRepo

    ContainerDeploymentScenario: SingleRegion

    ContainerEnableMetrics: false

    ContainerGameServerBuildPath: 

    ContainerGameServerExecutable: 

    ContainerDockerImageId: 

    ContainerECRRepositoryName: 

    ContainerECRRepositoryUri: 

    ContainerECRImageUri: 

    ContainerECRImageId: 

    ContainerPortRange: 

    ContainerTotalMemory: 

    ContainerTotalVcpu: 

    ContainerGameName: 

    ContainerImageTag: 

    IsContainerImageBuilding: false

    IsContainerImageBuilt: false

    IsECRRepoCreated: false

    IsContainerPushedToECR: false

    IsCGDDeploying: false

    IsCGDDeployed: false

    DeploymentScenario: SingleRegion

    DeploymentGameName: 

    ManagedEC2FleetName: 

    BuildName: 

    LaunchParameters: 

    BuildOperatingSystem: 

    EnableMetrics: false

    DeploymentBuildFilePath: 

    DeploymentBuildFolderPath: 

CurrentBucketName: highstreet-dev
...
