version: 1
LastOpenTab: Credentials
CurrentRegion: us-west-2
CurrentBucketName: gladiator-dev
CurrentProfileName: default
UserProfiles: >+
  - Region: us-west-2

    Name: Omar

    BucketName: 

    AnywhereFleetName: 

    AnywhereFleetId: 

    AnywhereFleetLocation: 

    ComputeName: 

    IpAddress: 

    WebSocketUrl: 

    ContainerDeploymentInProgress: false

    ContainersDeploymentComplete: false

    ContainerQuestionnaireScenario: NoContainerImageNoExistingEcrRepo

    ContainerDeploymentScenario: SingleRegion

    ContainerEnableMetrics: false

    ContainerGameServerBuildPath: 

    ContainerGameServerExecutable: 

    ContainerDockerImageId: 

    ContainerECRRepositoryName: 

    ContainerECRRepositoryUri: 

    ContainerECRImageUri: 

    ContainerECRImageId: 

    ContainerPortRange: 

    ContainerTotalMemory: 

    ContainerTotalVcpu: 

    ContainerGameName: 

    ContainerImageTag: 

    IsContainerImageBuilding: false

    IsContainerImageBuilt: false

    IsECRRepoCreated: false

    IsContainerPushedToECR: false

    IsCGDDeploying: false

    IsCGDDeployed: false

    DeploymentScenario: SingleRegion

    DeploymentGameName: 

    ManagedEC2FleetName: 

    BuildName: 

    LaunchParameters: 

    BuildOperatingSystem: 

    EnableMetrics: false

    DeploymentBuildFilePath: 

    DeploymentBuildFolderPath: 

  - Region: us-west-2

    Name: default

    BucketName: highstreet-dev

    AnywhereFleetName: 

    AnywhereFleetId: 

    AnywhereFleetLocation: 

    ComputeName: 

    IpAddress: 

    WebSocketUrl: 

    ContainerDeploymentInProgress: false

    ContainersDeploymentComplete: false

    ContainerQuestionnaireScenario: NoContainerImageNoExistingEcrRepo

    ContainerDeploymentScenario: SingleRegion

    ContainerEnableMetrics: false

    ContainerGameServerBuildPath: 

    ContainerGameServerExecutable: 

    ContainerDockerImageId: 

    ContainerECRRepositoryName: 

    ContainerECRRepositoryUri: 

    ContainerECRImageUri: 

    ContainerECRImageId: 

    ContainerPortRange: 

    ContainerTotalMemory: 

    ContainerTotalVcpu: 

    ContainerGameName: 

    ContainerImageTag: 

    IsContainerImageBuilding: false

    IsContainerImageBuilt: false

    IsECRRepoCreated: false

    IsContainerPushedToECR: false

    IsCGDDeploying: false

    IsCGDDeployed: false

    DeploymentScenario: SingleRegion

    DeploymentGameName: 

    ManagedEC2FleetName: 

    BuildName: 

    LaunchParameters: 

    BuildOperatingSystem: 

    EnableMetrics: false

    DeploymentBuildFilePath: 

    DeploymentBuildFolderPath: 

...
